api_version = "2026-07"

[[extensions]]
name = "t:name"
handle = "cart-transformer-extension"
type = "function"
uid = "d5a74675-640c-0712-c687-6cf57b96b0cbc605cfe2"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart_transform_run"

  [extensions.build]
  command = "cargo build --target=wasm32-unknown-unknown --release"
  path = "target/wasm32-unknown-unknown/release/cart-transformer-extension.wasm"
  watch = [ "src/**/*.rs" ]

  [extensions.ui.paths]
  create = "/"
  details = "/"
